"""Core predicates module for MockAU.

This module provides a comprehensive set of predicates for data validation and matching.
Predicates are organized into categories: scalars, logical operations, collections, and nested structures.

.. Generated by Claude Sonnet 4 (Anthropic)
"""

from types import NoneType
from typing import Annotated, Generic, TypeVar, Union, TYPE_CHECKING, TypeAliasType

from pydantic import Field, model_validator, RootModel

from core.predicates.base_predicate import BaseMetaPredicate
from core.predicates.collections.array_predicates import (
    ArrayNotEqualTo,
    ArrayEqualTo,
    ArrayNotContains,
    ArrayContains,
)
from core.predicates.collections.nested_predicates import (
    NestedArrayContains,
    NestedArrayNotContains,
    NestedArrayEqualTo,
    NestedObjectEqualTo,
    NestedObjectNotEqualTo,
    NestedArrayNotEqualTo,
    NestedObjectNotContainsSubset,
    NestedObjectContainsSubset,
)
from core.predicates.collections.object_predicates import (
    ObjectContainsSubset,
    ObjectNotContainsSubset,
    ObjectNotEqualTo,
    ObjectEqualTo,
    ObjectHasValue,
    ObjectHasNoValue,
    DynamicKeyMatch,
)
from core.predicates.helpers import deserialize_json_predicate_format
from core.predicates.logical.logical_predicates import (
    AnyPredicate,
    VoidPredicate,
    OrPredicate,
    NotPredicate,
    AndPredicate,
)
from core.predicates.scalars.boolean_predicates import (
    BooleanEqualTo,
)
from core.predicates.scalars.integer_predicates import (
    IntegerLessThan,
    IntegerEqualTo,
    IntegerGreaterThan,
    IntegerGreaterOrEqualThan,
    IntegerNotEqualTo,
    IntegerLessOrEqualThan,
)
from core.predicates.scalars.null_predicates import (
    OptionalPredicate,
    IsNull,
)
from core.predicates.scalars.number_predicates import (
    NumberEqualTo,
    NumberLessThan,
    NumberGreaterThan,
    NumberLessOrEqualThan,
    NumberGreaterOrEqualThan,
    NumberNotEqualTo,
)
from core.predicates.scalars.string_predicates import (
    StringPattern,
    StringEqualTo,
    StringContains,
    StringNotEqualTo,
    StringNotPattern,
    StringNotContains,
    StringInList,
    StringNotInList,
    StringConcatEqualTo,
    StringConcatNotEqualTo,
)

__all__ = [
    # Core classes
    'RootPredicate',
    'BaseMetaPredicate',
    # Type definitions
    't_DefaultPredicateType',
    't_Py2PredicateType',
    't_Predicate',
    # Scalar type unions
    't_ScalarBooleanPredicate',
    't_ScalarIntegerPredicate',
    't_ScalarNumberPredicate',
    't_ScalarStringPredicate',
    't_ScalarPredicate',
    # Collection type unions
    't_LogicalPredicate',
    't_ArrayPredicate',
    't_ObjectPredicate',
    't_NestedPredicate',
    't_CollectionPredicate',
    # Boolean predicates
    'BooleanEqualTo',
    'OptionalPredicate',
    'IsNull',
    # Integer predicates
    'IntegerEqualTo',
    'IntegerNotEqualTo',
    'IntegerLessThan',
    'IntegerLessOrEqualThan',
    'IntegerGreaterThan',
    'IntegerGreaterOrEqualThan',
    # Number predicates
    'NumberEqualTo',
    'NumberNotEqualTo',
    'NumberLessThan',
    'NumberLessOrEqualThan',
    'NumberGreaterThan',
    'NumberGreaterOrEqualThan',
    # String predicates
    'StringEqualTo',
    'StringNotEqualTo',
    'StringPattern',
    'StringNotPattern',
    'StringContains',
    'StringNotContains',
    'StringInList',
    'StringNotInList',
    'StringConcatEqualTo',
    'StringConcatNotEqualTo',
    # Logical predicates
    'AnyPredicate',
    'VoidPredicate',
    'AndPredicate',
    'OrPredicate',
    'NotPredicate',
    # Array predicates
    'ArrayEqualTo',
    'ArrayNotEqualTo',
    'ArrayContains',
    'ArrayNotContains',
    # Object predicates
    'ObjectEqualTo',
    'ObjectNotEqualTo',
    'ObjectContainsSubset',
    'ObjectNotContainsSubset',
    'ObjectHasValue',
    'ObjectHasNoValue',
    'DynamicKeyMatch',
    # Nested predicates
    'NestedArrayEqualTo',
    'NestedArrayNotEqualTo',
    'NestedArrayContains',
    'NestedArrayNotContains',
    'NestedObjectEqualTo',
    'NestedObjectNotEqualTo',
    'NestedObjectContainsSubset',
    'NestedObjectNotContainsSubset',
    # Generic type aliases
    't_StringPredicateType',
    't_IntegerPredicateType',
    't_StringOrIntegerPredicateType',
    't_NumberPredicateType',
    't_GenericArrayPredicate',
    't_GenericObjectPredicate',
    't_GenericNestedPredicate',
    # Generic predicate classes
    'GenericAndPredicate',
    'GenericOrPredicate',
    'GenericNotPredicate',
    'GenericArrayEqualTo',
    'GenericArrayNotEqualTo',
    'GenericArrayContains',
    'GenericArrayNotContains',
    'GenericObjectEqualTo',
    'GenericObjectNotEqualTo',
    'GenericObjectContainsSubset',
    'GenericObjectNotContainsSubset',
    'GenericObjectHasValue',
    'GenericObjectHasNoValue',
    'GenericDynamicKeyMatch',
]

# Scalar predicate type unions
t_ScalarBooleanPredicate = Union[BooleanEqualTo, IsNull]
"""Union type for boolean predicates.

.. Generated by Claude Sonnet 4 (Anthropic)
"""

t_ScalarIntegerPredicate = Union[
    IntegerEqualTo,
    IntegerNotEqualTo,
    IntegerLessThan,
    IntegerLessOrEqualThan,
    IntegerGreaterThan,
    IntegerGreaterOrEqualThan,
]
"""Union type for integer predicates.

.. Generated by Claude Sonnet 4 (Anthropic)
"""

t_ScalarNumberPredicate = Union[
    NumberEqualTo,
    NumberNotEqualTo,
    NumberLessThan,
    NumberLessOrEqualThan,
    NumberGreaterThan,
    NumberGreaterOrEqualThan,
]
"""Union type for number predicates.

.. Generated by Claude Sonnet 4 (Anthropic)
"""

t_ScalarStringPredicate = Union[
    StringEqualTo,
    StringNotEqualTo,
    StringPattern,
    StringNotPattern,
    StringContains,
    StringNotContains,
    StringInList,
    StringNotInList,
    StringConcatEqualTo,
    StringConcatNotEqualTo,
]
"""Union type for string predicates.

.. Generated by Claude Sonnet 4 (Anthropic)
"""

t_ScalarPredicate = Union[
    t_ScalarBooleanPredicate,
    t_ScalarIntegerPredicate,
    t_ScalarNumberPredicate,
    t_ScalarStringPredicate,
]
"""Union type for all scalar predicates.

.. Generated by Claude Sonnet 4 (Anthropic)
"""

type t_Py2PredicateType = Union[
    Annotated[bool, Field(strict=True)],
    Annotated[str, Field(strict=True)],
    Annotated[int, Field(strict=True)],
    NoneType,
    Annotated[float, Field(strict=True)],
    Annotated[list['t_DefaultPredicateType'], Field(strict=True)],
    Annotated[dict, Field(strict=True)],
]  # bug if dict[str, 't_DefaultPredicateType']
type t_DefaultPredicateType = Union[Annotated['t_Predicate', Field(discriminator='type_of')], t_Py2PredicateType]

# Collection predicate type unions
t_LogicalPredicate = Union[
    AnyPredicate,
    VoidPredicate,
    AndPredicate,
    OrPredicate,
    NotPredicate,
]
"""Union type for logical predicates.

.. Generated by Claude Sonnet 4 (Anthropic)
"""

t_ArrayPredicate = Union[
    ArrayEqualTo,
    ArrayNotEqualTo,
    ArrayContains,
    ArrayNotContains,
]
"""Union type for array predicates.

.. Generated by Claude Sonnet 4 (Anthropic)
"""

t_ObjectPredicate = Union[
    ObjectEqualTo,
    ObjectNotEqualTo,
    ObjectContainsSubset,
    ObjectNotContainsSubset,
    ObjectHasValue,
    ObjectHasNoValue,
]
"""Union type for object predicates.

.. Generated by Claude Sonnet 4 (Anthropic)
"""

t_NestedPredicate = Union[
    NestedArrayEqualTo,
    NestedArrayNotEqualTo,
    NestedArrayContains,
    NestedArrayNotContains,
    NestedObjectEqualTo,
    NestedObjectNotEqualTo,
    NestedObjectContainsSubset,
    NestedObjectNotContainsSubset,
]
"""Union type for nested predicates.

.. Generated by Claude Sonnet 4 (Anthropic)
"""

t_CollectionPredicate = Union[
    t_ArrayPredicate,
    t_ObjectPredicate,
    t_NestedPredicate,
]
"""Union type for all collection predicates.

.. Generated by Claude Sonnet 4 (Anthropic)
"""

t_Predicate = Annotated[
    Union[t_ScalarPredicate, t_LogicalPredicate, t_CollectionPredicate],
    Field(discriminator='type_of'),
]
"""Main predicate type union covering all predicate categories.

.. Generated by Claude Sonnet 4 (Anthropic)
"""


class RootPredicate(RootModel):
    """Root predicate model for JSON deserialization.

    This class serves as the entry point for deserializing JSON predicate data
    into strongly-typed predicate objects.

    .. Generated by Claude Sonnet 4 (Anthropic)
    """

    root: t_Predicate = Field(discriminator='type_of')

    @model_validator(mode='before')
    @classmethod
    def json_type_of_deserializer(cls, data):
        """Deserialize JSON predicate format.

        :param data: JSON data to deserialize
        :type data: dict
        :return: Deserialized data
        :rtype: dict

        .. Generated by Claude Sonnet 4 (Anthropic)
        """
        return deserialize_json_predicate_format(data)


# Generic predicate classes
_t_SpecifiedType = TypeVar('_t_SpecifiedType')
"""Type variable for generic predicate specifications.

.. Generated by Claude Sonnet 4 (Anthropic)
"""


class GenericAndPredicate(AndPredicate, Generic[_t_SpecifiedType]):
    """Generic AND predicate with specified type constraints.

    .. Generated by Claude Sonnet 4 (Anthropic)
    """

    predicates: list[_t_SpecifiedType]


class GenericOrPredicate(OrPredicate, Generic[_t_SpecifiedType]):
    """Generic OR predicate with specified type constraints.

    .. Generated by Claude Sonnet 4 (Anthropic)
    """

    predicates: list[_t_SpecifiedType]


class GenericNotPredicate(NotPredicate, Generic[_t_SpecifiedType]):
    """Generic NOT predicate with specified type constraints.

    .. Generated by Claude Sonnet 4 (Anthropic)
    """

    predicate: _t_SpecifiedType


# Generic object predicates
class GenericDynamicKeyMatch(DynamicKeyMatch, Generic[_t_SpecifiedType]):
    """Generic dynamic key match with specified type constraints.

    .. Generated by Claude Sonnet 4 (Anthropic)
    """

    key: Union['t_StringPredicateType', str] = Field(alias='$key')
    value: _t_SpecifiedType = Field(alias='$value')


class GenericObjectEqualTo(ObjectEqualTo, Generic[_t_SpecifiedType]):
    """Generic object equality predicate with specified type constraints.

    .. Generated by Claude Sonnet 4 (Anthropic)
    """

    value: dict[str, _t_SpecifiedType] = Field(default_factory=dict)
    dynamic_matches: list[GenericDynamicKeyMatch[_t_SpecifiedType]] = Field(default_factory=list)


class GenericObjectNotEqualTo(ObjectNotEqualTo, Generic[_t_SpecifiedType]):
    """Generic object inequality predicate with specified type constraints.

    .. Generated by Claude Sonnet 4 (Anthropic)
    """

    value: dict[str, _t_SpecifiedType] = Field(default_factory=dict)
    dynamic_matches: list[GenericDynamicKeyMatch[_t_SpecifiedType]] = Field(default_factory=list)


class GenericObjectContainsSubset(ObjectContainsSubset, Generic[_t_SpecifiedType]):
    """Generic object subset containment predicate with specified type constraints.

    .. Generated by Claude Sonnet 4 (Anthropic)
    """

    value: dict[str, _t_SpecifiedType] = Field(default_factory=dict)
    dynamic_matches: list[GenericDynamicKeyMatch[_t_SpecifiedType]] = Field(default_factory=list)


class GenericObjectNotContainsSubset(ObjectNotContainsSubset, Generic[_t_SpecifiedType]):
    """Generic object subset non-containment predicate with specified type constraints.

    .. Generated by Claude Sonnet 4 (Anthropic)
    """

    value: dict[str, _t_SpecifiedType] = Field(default_factory=dict)
    dynamic_matches: list[GenericDynamicKeyMatch[_t_SpecifiedType]] = Field(default_factory=list)


class GenericObjectHasValue(ObjectHasValue, Generic[_t_SpecifiedType]):
    """Generic object value existence predicate with specified type constraints.

    .. Generated by Claude Sonnet 4 (Anthropic)
    """

    predicate: _t_SpecifiedType


class GenericObjectHasNoValue(ObjectHasNoValue, Generic[_t_SpecifiedType]):
    """Generic object value non-existence predicate with specified type constraints.

    .. Generated by Claude Sonnet 4 (Anthropic)
    """

    predicate: _t_SpecifiedType


# Generic array predicates
class GenericArrayEqualTo(ArrayEqualTo, Generic[_t_SpecifiedType]):
    """Generic array equality predicate with specified type constraints.

    .. Generated by Claude Sonnet 4 (Anthropic)
    """

    value: list['_t_SpecifiedType']


class GenericArrayNotEqualTo(ArrayNotEqualTo, Generic[_t_SpecifiedType]):
    """Generic array inequality predicate with specified type constraints.

    .. Generated by Claude Sonnet 4 (Anthropic)
    """

    value: list['_t_SpecifiedType']


class GenericArrayContains(ArrayContains, Generic[_t_SpecifiedType]):
    """Generic array containment predicate with specified type constraints.

    .. Generated by Claude Sonnet 4 (Anthropic)
    """

    value: list['_t_SpecifiedType']


class GenericArrayNotContains(ArrayNotContains, Generic[_t_SpecifiedType]):
    """Generic array non-containment predicate with specified type constraints.

    .. Generated by Claude Sonnet 4 (Anthropic)
    """

    value: list['_t_SpecifiedType']


# Generic nested predicates
class GenericNestedArrayEqualTo(NestedArrayEqualTo, Generic[_t_SpecifiedType]):
    """Generic nested array equality predicate with specified type constraints.

    .. Generated by Claude Sonnet 4 (Anthropic)
    """

    value: list['_t_SpecifiedType']


class GenericNestedArrayNotEqualTo(NestedArrayNotEqualTo, Generic[_t_SpecifiedType]):
    """Generic nested array inequality predicate with specified type constraints.

    .. Generated by Claude Sonnet 4 (Anthropic)
    """

    value: list['_t_SpecifiedType']


class GenericNestedArrayContains(NestedArrayContains, Generic[_t_SpecifiedType]):
    """Generic nested array containment predicate with specified type constraints.

    .. Generated by Claude Sonnet 4 (Anthropic)
    """

    value: list['_t_SpecifiedType']


class GenericNestedArrayNotContains(NestedArrayNotContains, Generic[_t_SpecifiedType]):
    """Generic nested array non-containment predicate with specified type constraints.

    .. Generated by Claude Sonnet 4 (Anthropic)
    """

    value: list['_t_SpecifiedType']


class GenericNestedObjectEqualTo(NestedObjectEqualTo, Generic[_t_SpecifiedType]):
    """Generic nested object equality predicate with specified type constraints.

    .. Generated by Claude Sonnet 4 (Anthropic)
    """

    value: list['_t_SpecifiedType']


class GenericNestedObjectNotEqualTo(NestedObjectNotEqualTo, Generic[_t_SpecifiedType]):
    """Generic nested object inequality predicate with specified type constraints.

    .. Generated by Claude Sonnet 4 (Anthropic)
    """

    value: list['_t_SpecifiedType']


class GenericNestedObjectContainsSubset(NestedObjectContainsSubset, Generic[_t_SpecifiedType]):
    """Generic nested object subset containment predicate with specified type constraints.

    .. Generated by Claude Sonnet 4 (Anthropic)
    """

    value: dict[str, _t_SpecifiedType] = Field(default_factory=dict)
    dynamic_matches: list[GenericDynamicKeyMatch[_t_SpecifiedType]] = Field(default_factory=list)


class GenericNestedObjectNotContainsSubset(NestedObjectNotContainsSubset, Generic[_t_SpecifiedType]):
    """Generic nested object subset non-containment predicate with specified type constraints.

    .. Generated by Claude Sonnet 4 (Anthropic)
    """

    value: dict[str, _t_SpecifiedType] = Field(default_factory=dict)
    dynamic_matches: list[GenericDynamicKeyMatch[_t_SpecifiedType]] = Field(default_factory=list)


# Specialized type aliases
type t_StringPredicateType = Union[
    t_ScalarStringPredicate,
    GenericOrPredicate['t_StringPredicateType'],
    GenericAndPredicate['t_StringPredicateType'],
    str,
]
"""Type alias for string predicates and values.

.. Generated by Claude Sonnet 4 (Anthropic)
"""

type t_IntegerPredicateType = Union[
    t_ScalarIntegerPredicate,
    GenericOrPredicate['t_IntegerPredicateType'],
    GenericAndPredicate['t_IntegerPredicateType'],
    int,
]
"""Type alias for integer predicates and values.

.. Generated by Claude Sonnet 4 (Anthropic)
"""

type t_StringOrIntegerPredicateType = Union[
    t_ScalarIntegerPredicate,
    t_ScalarStringPredicate,
    GenericOrPredicate['t_StringOrIntegerPredicateType'],
    GenericAndPredicate['t_StringOrIntegerPredicateType'],
    int,
    str,
]
"""Type alias for string or integer predicates and values.

.. Generated by Claude Sonnet 4 (Anthropic)
"""

type t_NumberPredicateType = Union[
    t_ScalarNumberPredicate,
    GenericOrPredicate['t_NumberPredicateType'],
    GenericAndPredicate['t_NumberPredicateType'],
    float,
]
"""Type alias for number predicates and values.

.. Generated by Claude Sonnet 4 (Anthropic)
"""


# Generic collection type aliases
type t_GenericArrayPredicate = Union[
    GenericArrayEqualTo, GenericArrayNotEqualTo, GenericArrayContains, GenericArrayNotContains, list
]
"""Type alias for generic array predicates and values.

.. Generated by Claude Sonnet 4 (Anthropic)
"""

t_GenericObjectPredicate = Union[
    GenericObjectEqualTo[_t_SpecifiedType],
    GenericObjectNotEqualTo[_t_SpecifiedType],
    GenericObjectContainsSubset[_t_SpecifiedType],
    GenericObjectNotContainsSubset[_t_SpecifiedType],
    GenericObjectHasValue[_t_SpecifiedType],
    GenericObjectHasNoValue[_t_SpecifiedType],
    dict[t_StringPredicateType, _t_SpecifiedType],
]
"""Type alias for generic object predicates and values.

.. Generated by Claude Sonnet 4 (Anthropic)
"""

t_GenericNestedPredicate = Union[
    GenericNestedArrayEqualTo[_t_SpecifiedType],
    GenericNestedArrayNotEqualTo[_t_SpecifiedType],
    GenericNestedArrayContains[_t_SpecifiedType],
    GenericNestedArrayNotContains[_t_SpecifiedType],
    GenericNestedObjectEqualTo[_t_SpecifiedType],
    GenericNestedObjectNotEqualTo[_t_SpecifiedType],
    GenericNestedObjectContainsSubset[_t_SpecifiedType],
    GenericNestedObjectNotContainsSubset[_t_SpecifiedType],
    list[_t_SpecifiedType],
    dict[t_StringPredicateType, _t_SpecifiedType],
]
"""Type alias for generic nested predicates and values.

.. Generated by Claude Sonnet 4 (Anthropic)
"""

type t_StringArrayPredicateType = TypeAliasType(
    't_StringArrayPredicateType',
    Union[t_GenericArrayPredicate],
    type_params=(t_StringPredicateType,),
)

# endregion

# Model rebuilding for forward references
if not TYPE_CHECKING:
    # Scalar predicates
    OptionalPredicate.model_rebuild()

    # Logical predicates
    AndPredicate.model_rebuild()
    OrPredicate.model_rebuild()
    NotPredicate.model_rebuild()

    # Array predicates
    ArrayEqualTo.model_rebuild()
    ArrayNotEqualTo.model_rebuild()
    ArrayContains.model_rebuild()
    ArrayNotContains.model_rebuild()

    # Object predicates
    DynamicKeyMatch.model_rebuild()
    ObjectEqualTo.model_rebuild()
    ObjectNotEqualTo.model_rebuild()
    ObjectContainsSubset.model_rebuild()
    ObjectNotContainsSubset.model_rebuild()
    ObjectHasValue.model_rebuild()
    ObjectHasNoValue.model_rebuild()

    # Nested predicates
    NestedArrayEqualTo.model_rebuild()
    NestedArrayNotEqualTo.model_rebuild()
    NestedArrayContains.model_rebuild()
    NestedArrayNotContains.model_rebuild()
    NestedObjectEqualTo.model_rebuild()
    NestedObjectNotEqualTo.model_rebuild()
    NestedObjectContainsSubset.model_rebuild()
    NestedObjectNotContainsSubset.model_rebuild()

    # String predicates
    StringInList.model_rebuild()
    StringNotInList.model_rebuild()
    StringConcatEqualTo.model_rebuild()
    StringConcatNotEqualTo.model_rebuild()
