from enum import Enum


class PredicateType(Enum):
    """Enumeration representing data types for predicates.

    :cvar Boolean: Boolean type (true/false)
    :cvar Integer: Integer number type
    :cvar Real: Real number type
    :cvar String: String type
    :cvar Object: JSON object type
    :cvar Array: Array type
    :cvar Null: Null type
    :cvar Any: Any type

    .. Docstring generated by Gemini 2.5 Flash
    """

    Boolean = 'Boolean'
    Integer = 'Integer'
    Real = 'Real'
    String = 'String'
    Object = 'Object'
    Array = 'Array'
    Null = 'Null'
    Any = 'Any'
    Undefined = 'Undefined'


PREDICATE_TYPE_TO_PYTHON_TYPE = {
    PredicateType.Boolean: bool,
    PredicateType.Integer: int,
    PredicateType.Real: float,
    PredicateType.String: str,
    PredicateType.Object: dict,
    PredicateType.Array: list,
    PredicateType.Null: type(None),
    PredicateType.Any: object,
}

ALLOWED_POOL_PREDICATE_TYPES = {
    PredicateType.Null,
    PredicateType.Boolean,
    PredicateType.Integer,
    PredicateType.Real,
    PredicateType.String,
    PredicateType.Object,
    PredicateType.Array,
}

DEFAULT_SOLVER_TIMEOUT = 600
