from enum import Enum


class PredicateType(Enum):
    """Enumeration representing data types for predicates.

    :cvar Boolean: Boolean type (true/false)
    :cvar Integer: Integer number type
    :cvar Real: Real number type
    :cvar String: String type
    :cvar Object: JSON object type
    :cvar Array: Array type
    :cvar Null: Null type
    :cvar Any: Any type

    .. Docstring generated by Gemini 2.5 Flash
    """

    Boolean = 'Boolean'
    Integer = 'Integer'
    Real = 'Real'
    String = 'String'
    Object = 'Object'
    Array = 'Array'
    Null = 'Null'
    Any = 'Any'
    Undefined = 'Undefined'


DEFAULT_SOLVER_TIMEOUT = 100
