from typing import Literal

import z3

from core.predicates.base_predicate import BaseScalarPredicate, PredicateType, VariableContext


class BaseIntegerPredicate(BaseScalarPredicate):
    """Base class for integer predicates.

    .. Generated by Claude Sonnet 4 (Anthropic)
    """

    @property
    def predicate_types(self):
        """Get supported predicate types for this class.

        :return: Set containing only Integer type
        :rtype: set[PredicateType]

        .. Generated by Claude Sonnet 4 (Anthropic)
        """
        return {PredicateType.Integer}

    def get_all_predicates(self):
        yield self


class IntegerEqualTo(BaseIntegerPredicate):
    """Predicate for checking if an integer value is equal to a specific value.

    .. Generated by Claude Sonnet 4 (Anthropic)
    """

    type_of: Literal['$-mockau-integer-eq'] = '$-mockau-integer-eq'
    value: int

    def verify(self, value):
        """Verify if value equals the expected integer.

        :param value: Value to verify
        :type value: Any
        :return: True if value matches
        :rtype: bool

        .. Generated by Claude Sonnet 4 (Anthropic)
        """
        return isinstance(value, int) and value == self.value

    def __invert__(self):
        """Create inverted predicate.

        :return: IntegerNotEqualTo predicate
        :rtype: IntegerNotEqualTo

        .. Generated by Claude Sonnet 4 (Anthropic)
        """
        return IntegerNotEqualTo(value=self.value, var=self.var)

    def to_z3(self, ctx: VariableContext):
        """Convert the integer equality predicate to a Z3 expression.

        :param ctx: The variable context for Z3 expressions
        :type ctx: VariableContext
        :return: A Z3 expression representing the equality constraint
        :rtype: z3.ExprRef

        .. Generated by Claude Sonnet 4 (Anthropic)
        """
        integer_variable = ctx.get_variable(self.predicate_type)
        ctx.set_as_user_variable(self.var)
        return z3.And(integer_variable == z3.IntVal(self.value, ctx=ctx.z3_context), ctx.json_type_variable.is_int())


class IntegerNotEqualTo(BaseIntegerPredicate):
    type_of: Literal['$-mockau-integer-neq'] = '$-mockau-integer-neq'
    value: int

    def normalize_to_canonical_form(self):
        from core.predicates import OrPredicate

        return OrPredicate(
            predicates=[IntegerGreaterThan(value=self.value), IntegerLessThan(value=self.value)],
        ).normalize_to_canonical_form()

    def verify(self, value):
        return isinstance(value, int) and value != self.value

    def __invert__(self):
        return IntegerEqualTo(value=self.value, var=self.var)

    def to_z3(self, ctx: VariableContext):
        integer_variable = ctx.get_variable(self.predicate_type)
        ctx.set_as_user_variable(self.var)
        return z3.And(integer_variable != z3.IntVal(self.value, ctx=ctx.z3_context), ctx.json_type_variable.is_int())


class IntegerGreaterThan(BaseIntegerPredicate):
    """Predicate for checking if an integer value is greater than a specific value.

    .. Docstring created by Gemini 2.5 Flash
    """

    type_of: Literal['$-mockau-integer-gt'] = '$-mockau-integer-gt'
    value: int

    def verify(self, value):
        return isinstance(value, int) and value > self.value

    def __invert__(self):
        return IntegerLessOrEqualThan(value=self.value, var=self.var)

    def to_z3(self, ctx: VariableContext):
        """Convert the integer greater-than predicate to a Z3 expression.

        :param ctx: The variable context for Z3 expressions.
        :type ctx: VariableContext
        :return: A Z3 expression representing the greater-than constraint.
        :rtype: z3.ExprRef

        .. Docstring created by Gemini 2.5 Flash
        """
        integer_variable = ctx.get_variable(self.predicate_type)
        ctx.set_as_user_variable(self.var)
        return z3.And(integer_variable > z3.IntVal(self.value, ctx=ctx.z3_context), ctx.json_type_variable.is_int())


class IntegerGreaterOrEqualThan(BaseIntegerPredicate):
    """Predicate for checking if an integer value is greater than or equal to a specific value.

    .. Docstring created by Gemini 2.5 Flash
    """

    type_of: Literal['$-mockau-integer-gte'] = '$-mockau-integer-gte'
    value: int

    def normalize_to_canonical_form(self):
        from core.predicates import OrPredicate

        return OrPredicate(
            predicates=[IntegerGreaterThan(value=self.value), IntegerEqualTo(value=self.value)],
        ).normalize_to_canonical_form()

    def verify(self, value):
        return isinstance(value, int) and value >= self.value

    def __invert__(self):
        return IntegerLessThan(value=self.value, var=self.var)

    def to_z3(self, ctx: VariableContext):
        """Convert the integer greater-than-or-equal-to predicate to a Z3 expression.

        :param ctx: The variable context for Z3 expressions.
        :type ctx: VariableContext
        :return: A Z3 expression representing the greater-than-or-equal-to constraint.
        :rtype: z3.ExprRef

        .. Docstring created by Gemini 2.5 Flash
        """
        integer_variable = ctx.get_variable(self.predicate_type)
        ctx.set_as_user_variable(self.var)
        return z3.And(integer_variable >= z3.IntVal(self.value, ctx=ctx.z3_context), ctx.json_type_variable.is_int())


class IntegerLessThan(BaseIntegerPredicate):
    """Predicate for checking if an integer value is less than a specific value.

    .. Docstring created by Gemini 2.5 Flash
    """

    type_of: Literal['$-mockau-integer-lt'] = '$-mockau-integer-lt'
    value: int

    def verify(self, value):
        return isinstance(value, int) and value < self.value

    def __invert__(self):
        return IntegerGreaterOrEqualThan(value=self.value, var=self.var)

    def to_z3(self, ctx: VariableContext):
        """Convert the integer less-than predicate to a Z3 expression.

        :param ctx: The variable context for Z3 expressions.
        :type ctx: VariableContext
        :return: A Z3 expression representing the less-than constraint.
        :rtype: z3.ExprRef

        .. Docstring created by Gemini 2.5 Flash
        """
        integer_variable = ctx.get_variable(self.predicate_type)
        ctx.set_as_user_variable(self.var)
        return z3.And(integer_variable < z3.IntVal(self.value, ctx=ctx.z3_context), ctx.json_type_variable.is_int())


class IntegerLessOrEqualThan(BaseIntegerPredicate):
    """Predicate for checking if an integer value is less than or equal to a specific value.

    .. Docstring created by Gemini 2.5 Flash
    """

    type_of: Literal['$-mockau-integer-lte'] = '$-mockau-integer-lte'
    value: int

    def normalize_to_canonical_form(self):
        from core.predicates import OrPredicate

        return OrPredicate(
            predicates=[IntegerLessThan(value=self.value), IntegerEqualTo(value=self.value)],
        ).normalize_to_canonical_form()

    def verify(self, value):
        return isinstance(value, int) and value <= self.value

    def __invert__(self):
        return IntegerGreaterThan(value=self.value, var=self.var)

    def to_z3(self, ctx: VariableContext):
        """Convert the integer less-than-or-equal-to predicate to a Z3 expression.

        :param ctx: The variable context for Z3 expressions.
        :type ctx: VariableContext
        :return: A Z3 expression representing the less-than-or-equal-to constraint.
        :rtype: z3.ExprRef

        .. Docstring created by Gemini 2.5 Flash
        """
        integer_variable = ctx.get_variable(self.predicate_type)
        ctx.set_as_user_variable(self.var)
        return z3.And(integer_variable <= z3.IntVal(self.value, ctx=ctx.z3_context), ctx.json_type_variable.is_int())
